### ISSUE TITLE
Can not use polaris audit --helm-chart inside the polaris container.

### ISSUE THREAD

**Issue by devopsInterviews** [FairwindsOps/polaris#1042]
### What happened?

Hi Im using the latest polaris container (9.0.1) and use this command inside the container:

polaris audit --helm-chart /tmp/my-chart --helm-values /tmp/my-chart/values.yaml

I got this error:

ERRO[0000]
ERRO[0000] Couldn't process helm chart: exec: "helm": executable file not found in $PATH

Why it says we need helm as part of the container? should't it be part of it in order to use the tool?

### What did you expect to happen?

To show the regular security check

### How can we reproduce this?

Run the 9.0.1 version

### Version

9.0.1

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
The container is built as minimally as possible in order to avoid external dependencies and extra size - it's essentially just the polaris binary.

The `--helm-chart` feature is a convenience that wraps `helm template` and pipes it into a `polaris audit` command. 

If you need to run polaris against helm charts, I would recommend that you install helm and polaris in your CI process - as they are both small binaries that should be quick to install.

**Comment by devopsInterviews** [comment]
@sudermanjr thanks for the quick answer!
So there is no official docker image that combines both?
Should I build one on my own?
