### ISSUE TITLE
Custom checks?

### ISSUE THREAD

**Issue by vvostryakov** [FairwindsOps/polaris#142]
Is it possible to add custom checks?

**Comment by bobby-brennan** [comment]
Hi there - thanks for reaching out!

Right now custom checks aren't possible, but we're certainly open to pull requests with new checks that might benefit the community. Do you have an idea for what you'd like to implement?

I'm going to leave this open as a feature request, as it's something we've been considering.

**Comment by vvostryakov** [comment]
Hi Bobby, thanks for the answer.

My suggestions:
- A minimal set of replicas (to detect HA issues)
- A resource usage check (to detect the situation when service most of the time in standby mode or requests more than it actually needs)
- A process amount check inside the container (to detect the situation when container actually contains a lot of processes or forks inside)
- A '/metrics' check

Probably some of them will be useful. 

Also, it can be useful to integrate existing chaos/security checks, like Netflix chaos monkey for example.

**Comment by bobby-brennan** [comment]
These are great ideas!

Right now, we're focusing on just checking configuration. A replica minimum definitely fits in, but resource usage and process amount might be out of scope since they require ongoing access to a running container/pod. That said, we may expand the scope to include stuff like this in the future.

What did you have in mind for the `/metrics` check?

**Comment by vvostryakov** [comment]
About '/metrics' check. 

That it exists and have anything. So we can detect the situation when the application doesn't report anything.

**Comment by rbren** [comment]
This is implemented now, using JSON Schema
