### ISSUE TITLE
Please provide additional checks like Podrestartpolicy or maxretries

### ISSUE THREAD

**Issue by sagarprusty** [FairwindsOps/polaris#199]
Polaris needs some additional validational checks like Pod's restart policy or maxretries so that it can monitor the usage of such parameters in the kubernetes deployment. 

**Reason to add:** The containers get restarted constantly whenever they fail. This might be because of system issues or some other factors. It will keep on failing even if it retries a lot of time.
If we don’t have the maxRetries on our pod/deployment, the pod will always retry, however it will not succeed and retries take a lot of time and resource.

**Comment by rbren** [comment]
This could now be accomplished by creating the necessary JSON schema, but turning these checks off by default.

**Comment by mambax** [comment]
Couldn't we start somewhere a best practice folder inside the repo? With some clear naming pattern? We'd also like to learn from others but examples are nowhere to be found or spread around the internet 😭

**Comment by rbren** [comment]
@mambax I think we chatted a bit about this, but what would you like to see in addition to the [custom checks directory](https://github.com/FairwindsOps/polaris/tree/master/checks)?

Maybe we should also encourage folks to contribute their checks back there?

**Comment by mambax** [comment]
Hi @rbren 
> Maybe we should also encourage folks to contribute their checks back there?
That is more what I meant.
Also what would have helped me tbh is that the config file lies separately from the rest of the files. So that you can hand it seamlessly to the CLI. The helm charts here https://github.com/FairwindsOps/charts/tree/master/stable/polaris has the config inside the values.yaml making it 'useless' for the CLI.

I have re-constructed the ConfigMap template to
```
config.yaml: |-
{{ .Files.Get "config.yaml" | indent 4 }}
```
directly import my config.
Like that I can throw it into the CLI.

I feel like generally the enablement comes a bit too short. I can note down more tomorrow or the next days 🤝
