### ISSUE TITLE
Webhook certs secret name mis-match when using Helm and non-default release name

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/polaris#211]
### Installation Process
 

helm install, using latest

### Polaris Version

```
0.4
```

### Expected Behavior

wehbook works

### Actual Behavior

webhook does not work

### Steps to Reproduce

```
helm upgrade --install polaris reactiveops-stable/polaris --namespace polaris   --set webhook.enable=true --set dashboard.enable=false
```

### Additional Context

```
$ k get po -n polaris
NAME                                  READY   STATUS             RESTARTS   AGE
polaris-wh-webhook-748ddb8794-56v7c   0/1     CrashLoopBackOff   2          37s
$ k logs polaris-wh-webhook-748ddb8794-56v7c
time="2019-10-04T20:44:03Z" level=info msg="Setting up webhook server"
time="2019-10-04T20:44:03Z" level=info msg="Polaris webhook server listening on port 9876"
time="2019-10-04T20:44:03Z" level=error msg="Error starting manager: open /opt/cert/key.pem: no such file or directory"
```

**Comment by rbren** [comment]
More clues!

When installing with name `polaris` in namespace `polaris`, everything works fine. But setting name `polaris-bad` and namespace `polaris-bad` fails.

It looks like the certs are not being populated in the latter case. But I'm not yet sure where that's happening.

```
$ k describe secret polaris-bad-webhook
Name:         polaris-bad-webhook
Namespace:    polaris-bad
Labels:       app=polaris
              app.kubernetes.io/instance=polaris-bad
              app.kubernetes.io/managed-by=Tiller
              app.kubernetes.io/name=polaris
              helm.sh/chart=polaris-0.5.1
Annotations:  <none>

Type:  Opaque

Data
====
cert.pem:  0 bytes

$ k describe secret polaris-webhook
Name:         polaris-webhook
Namespace:    polaris-bad
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
ca-cert.pem:  1038 bytes
ca-key.pem:   1679 bytes
cert.pem:     1074 bytes
key.pem:      1675 bytes
```

**Comment by ivanfetch** [comment]
@rbren We could either change how the webhook setup writes its certificates, or use a static secret name in the Helm chart to match what the webhook setup uses. More detail below:

The Polaris call to `sigs.k8s.io/controller-runtime/pkg/webhook.NewServer()` includes `Secret` in the `webhook.ServerOptions -> BootstrapOptions` which uses the static secret name `polaris-webhook`. If Polaris is installed using a Helm release name other than `polaris`, the webhook pod mounts the empty Helm-created secret (`{Helm release name}-webhook`) instead of the secret managed by the webhook during its setup process (`polaris-webhook`).

Comments in `webhook.NewServer()` state:

```
    // Secret is the location for storing the certificate for the admission server.
    // The server should have permission to create a secret in the namespace.     
    // This is optional. If unspecified, it will write to the filesystem.         
```

If we remove `Secret` from the call to `webhook.NewServer()` the webhook will write its own certificates to the container filesystem, but we will no longer be able to store them in a Kubernetes secret as [secret volumes are not writable as of Kube 1.8](https://github.com/kubernetes/kubernetes/issues/60814).

IF we don't want to store the certificates in a writable `EmptyDir` of the pod, we could update the Helm chart to use the same static secret name of `polaris-webhook`.

**Comment by ivanfetch** [comment]
This is resolved in [this charts PR 142](https://github.com/FairwindsOps/charts/pull/142).
