### ISSUE TITLE
Add exceptions with specific labels

### ISSUE THREAD

**Issue by devopssambareddy** [FairwindsOps/polaris#717]
**Is your feature request related to a problem? Please describe.**
Right now polaris supports exceptions with annotations only. It will be good even if it supports with labels also.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sudermanjr** [comment]
@devopssambareddy Can you share more about why you would want this functionality? I believe that general convention is for things that modify behavior (such as exemptions from policy) should be controlled by annotations, where labels should be used for identifying or categorizing things.

That doesn't mean we _couldn't_ do this, but I'm curious why this would be necessary. Also would definitely love @rbren or @lucasreed to chime in here.

**Comment by juanvasquezreyes** [comment]
This is a good idea, in my case I have many deployments in different namespaces that have a same label for example app.kubernetes.io/environment=prod, and more deployment will come with the same label, instead of specifying each deployment in the exclude list will be nice to exclude by this label certain checks

**Comment by juanvasquezreyes** [comment]
> I believe annotations are the right place for this sort of configuration.

but if we add annotations I have to redeploy or restart all the existing deployments that are currently running just to add the exceptions

**Comment by lucasreed** [comment]
For what it's worth, I am not fully opposed to supporting labels, but reading the kubernetes docs about the general usage of labels vs. annotations, my take is that this sort of configuration is generally done in annotations, which is why exceptions are currently set up like this.

If it's something enough people want, that's fine, but also needing to redeploy some apps isn't a good reason for us to dedicate time to this feature (in my opinion) 😄
