### ISSUE TITLE
add helm executable to docker image

### ISSUE THREAD

**Issue by johnqa** [FairwindsOps/polaris#787]
**Is your feature request related to a problem? Please describe.**
When I try to use Polaris docker image to scan a helm chart I am getting:
`time="2022-07-05T12:43:31Z" level=error
time="2022-07-05T12:43:31Z" level=info msg="Couldn't process helm chart: exec: \"helm\": executable file not found in $PATH"`

**Describe the solution you'd like**
I would be nice to add helm to Polaris image using something like:
`RUN apk update && apk add --no-cache curl bash openssl; curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3; chmod 700 get_helm.sh; /bin/bash get_helm.sh; rm get_helm.sh`

Thank you,
John

**Comment by sudermanjr** [comment]
👋🏼  Thanks for the suggestion.

Right now the image is intended to be run in the cluster as an admission controller and dashboard. As such, I would be very hesitant to introduce another dependency with its own potential vulnerabilities and changes to manage. 

Since Polaris is a relatively small binary, would it be a possibility to just install it and helm together in your CI pipeline?
