### ISSUE TITLE
Error: release name: invalid release name

### ISSUE THREAD

**Issue by jkroepke** [FairwindsOps/polaris#802]
### What happened?

Comming from docs https://polaris.docs.fairwinds.com/infrastructure-as-code/#running-in-a-ci-pipeline

I executed 

```
polaris audit --helm-chart ./charts/sealed-secrets --helm-values ./values.yaml 
```

and run into an error:

```
ERRO[0000] Error: release name "./charts/sealed-secrets": invalid release name, must match regex ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$ and the length must not be longer than 53 
INFO[0000] Couldn't process helm chart: exit status 1  
```

### What did you expect to happen?

A successful audit run.

### How can we reproduce this?

Running
```
polaris audit \
  --helm-chart ./deploy/chart \
  --helm-values ./deploy/chart/values.yml
```

### Version

7.0.1

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jkroepke** [comment]
Current workaround:

```
cd charts
polaris audit --helm-chart sealed-secrets --helm-values ../values.yaml 
```

What is not working:

```
cd charts
polaris audit --helm-chart ./sealed-secrets --helm-values ../values.yaml 
```
```
cd charts/sealed-secrets
polaris audit --helm-chart . --helm-values ../values.yaml 
```

**Comment by tomislater** [comment]
Maybe should we allow to pass this as a flag? Like namespace?

**Comment by tomislater** [comment]
Another workaround without `cd` (We use loop in our test and we don't want to mess with `cd` there :P): 

```
helm template charts/sealed-secrets --values values.yaml > ci-output.yaml
polaris audit --audit-path ci-output.yaml --format=pretty
```

**Comment by sudermanjr** [comment]
Hmmm, @rbren  your suggestion doesn't actually make sense to me. Testing this locally, I'm seeing that `helm template <absolute path anywhere> --generate-name` works fine, as well as `helm template ./folder/chart --generate-name` works fine as well.

Also, when I do `polaris audit --helm-chart <absolute path somewhere>` it works fine as well. The issue comes when you specifically use `./folder/chart` with polaris only. This doesn't make a ton of sense because the `--generate-name` flag is supposed to handle creating the release name.
