### ISSUE TITLE
looks like polaris doesn't support multiple values yaml file

### ISSUE THREAD

**Issue by vl-kp** [FairwindsOps/polaris#970]
### What happened?

polaris audit doesn't support multiple values yaml file
https://github.com/FairwindsOps/polaris/blob/master/cmd/polaris/audit.go#L212-L214

### What did you expect to happen?

```--helm-values ../../values.yaml --helm-values ../../1.yaml--helm-values 1.yaml``` should be supported as `helm -f`

### How can we reproduce this?

try multiple input values.yaml

### Version

8.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Can you please explain the actual problem with doing this, and the complete command that you are using? Polaris itself, and helm are two different tools, and it isn't clear where the issue lies. Please be as detailed as possible with your instructions to re-create the issue, and the actual error or issue encountered.
